CREATE DATABASE app_quizz;

CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,        -- ID único para cada usuario
    username VARCHAR(50) NOT NULL,            -- Nombre de usuario
    password VARCHAR(255) NOT NULL,            -- Contraseña (debería ser cifrada)
    email VARCHAR(100) NOT NULL UNIQUE,       -- Correo electrónico, debe ser único
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Fecha de creación de la cuenta
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP -- Fecha de actualización
);

CREATE TABLE preguntas (
    id INT AUTO_INCREMENT PRIMARY KEY,        -- ID único para cada pregunta
    pregunta_texto TEXT NOT NULL,             -- El texto de la pregunta
    categoria VARCHAR(50),                    -- (Opcional) Categoría o tema de la pregunta
    nivel INT DEFAULT 1,                      -- (Opcional) Nivel de dificultad de la pregunta (1, 2, 3)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Fecha de creación
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP -- Fecha de actualización
);

CREATE TABLE respuestas (
    id INT AUTO_INCREMENT PRIMARY KEY,        -- ID único para cada respuesta
    pregunta_id INT,                          -- ID de la pregunta relacionada
    respuesta_texto TEXT NOT NULL,            -- Texto de la respuesta
    es_correcta BOOLEAN DEFAULT FALSE,        -- Indicador si es la respuesta correcta (TRUE o FALSE)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Fecha de creación
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, -- Fecha de actualización
    FOREIGN KEY (pregunta_id) REFERENCES preguntas(id) -- Relación con la tabla `preguntas`
);


-- Insertar preguntas
INSERT INTO preguntas (pregunta_texto, categoria, nivel) VALUES
('¿Cuál es la capital de Francia?', 'Geografía', 1),
('¿Quién pintó la Mona Lisa?', 'Arte', 1),
('¿Qué gas respiramos los seres humanos?', 'Ciencia', 1),
('¿En qué continente se encuentra Egipto?', 'Geografía', 1),
('¿Cuántos continentes existen?', 'Geografía', 1),
('¿Cuál es el símbolo químico del oro?', 'Ciencia', 1),
('¿Quién escribió "Cien años de soledad"?', 'Literatura', 1),
('¿Qué es el ADN?', 'Ciencia', 1),
('¿Cuántos huesos tiene el cuerpo humano?', 'Ciencia', 1),
('¿Quién fue el primer presidente de los Estados Unidos?', 'Historia', 1),
('¿En qué año se llegó a la Luna?', 'Historia', 2),
('¿Qué es la teoría de la relatividad?', 'Ciencia', 2),
('¿Cuál es el río más largo del mundo?', 'Geografía', 2),
('¿Quién descubrió América?', 'Historia', 2),
('¿Qué animal es conocido como el "rey de la selva"?', 'Animales', 1),
('¿Qué planeta es conocido como el "planeta rojo"?', 'Astronomía', 1),
('¿Cuál es el idioma oficial de Brasil?', 'Lenguas', 1),
('¿Cuántos países tiene África?', 'Geografía', 2),
('¿En qué país se encuentra el Machu Picchu?', 'Geografía', 1),
('¿Quién fue el primer hombre en viajar al espacio?', 'Historia', 2),
('¿En qué año comenzó la Segunda Guerra Mundial?', 'Historia', 2),
('¿Qué es la fotosíntesis?', 'Biología', 1),
('¿Qué tipo de animal es una ballena?', 'Animales', 1),
('¿En qué país se inventó el teléfono?', 'Historia', 2),
('¿Cuál es la moneda de Japón?', 'Economía', 1),
('¿Qué significa "física"?', 'Ciencia', 1),
('¿Cuántos colores tiene el arcoíris?', 'Ciencia', 1),
('¿Quién fue Albert Einstein?', 'Ciencia', 2),
('¿Qué continente es el más grande?', 'Geografía', 1),
('¿Cuál es el océano más grande?', 'Geografía', 1),
('¿En qué año terminó la Primera Guerra Mundial?', 'Historia', 2),
('¿Qué es la teoría del Big Bang?', 'Ciencia', 2),
('¿En qué país se encuentra la Gran Muralla China?', 'Historia', 1),
('¿Cuál es la capital de España?', 'Geografía', 1),
('¿Quién fue el último emperador de China?', 'Historia', 2),
('¿Cuál es el elemento más abundante en el universo?', 'Ciencia', 2),
('¿Qué animal tiene más dientes?', 'Animales', 1),
('¿Qué océano se encuentra entre América y Europa?', 'Geografía', 1),
('¿Cuál es el país más poblado del mundo?', 'Geografía', 1),
('¿Qué es el cambio climático?', 'Ciencia', 2),
('¿Qué es el sol?', 'Astronomía', 1),
('¿Cuántos planetas hay en nuestro sistema solar?', 'Astronomía', 1),
('¿Cuál es el animal más rápido del mundo?', 'Animales', 1),
('¿Qué ciudad es conocida como la "Gran Manzana"?', 'Geografía', 1),
('¿Qué es el sistema solar?', 'Astronomía', 1),
('¿Qué es la biología?', 'Ciencia', 1),
('¿Cuál es la lengua más hablada en el mundo?', 'Lenguas', 1),
('¿Cuántos jugadores tiene un equipo de fútbol?', 'Deportes', 1),
('¿En qué país nació la pizza?', 'Cultura', 1),
('¿Qué es un huracán?', 'Ciencia', 2),
('¿Qué es el ciclo del agua?', 'Ciencia', 1);

INSERT INTO respuestas (pregunta_id, respuesta_texto, es_correcta) VALUES
(1, 'París', TRUE),
(1, 'Londres', FALSE),
(1, 'Madrid', FALSE),
(1, 'Roma', FALSE),
(2, 'Leonardo da Vinci', TRUE),
(2, 'Pablo Picasso', FALSE),
(2, 'Vincent van Gogh', FALSE),
(2, 'Michelangelo', FALSE),
(3, 'Oxígeno', TRUE),
(3, 'Nitrógeno', FALSE),
(3, 'Carbono', FALSE),
(3, 'Hidrógeno', FALSE),
(4, 'África', TRUE),
(4, 'Asia', FALSE),
(4, 'Europa', FALSE),
(4, 'América', FALSE),
(5, '7', TRUE),
(5, '6', FALSE),
(5, '5', FALSE),
(5, '8', FALSE),
(6, 'Au', TRUE),
(6, 'Ag', FALSE),
(6, 'Cu', FALSE),
(6, 'Fe', FALSE),
(7, 'Gabriel García Márquez', TRUE),
(7, 'Mario Vargas Llosa', FALSE),
(7, 'Jorge Luis Borges', FALSE),
(7, 'Carlos Fuentes', FALSE),
(8, 'Ácido desoxirribonucleico', TRUE),
(8, 'Ácido ribonucleico', FALSE),
(8, 'Proteína', FALSE),
(8, 'Lípido', FALSE),
(9, '206', TRUE),
(9, '150', FALSE),
(9, '250', FALSE),
(9, '300', FALSE),
(10, 'George Washington', TRUE),
(10, 'Abraham Lincoln', FALSE),
(10, 'Thomas Jefferson', FALSE),
(10, 'Theodore Roosevelt', FALSE),
(11, '1969', TRUE),
(11, '1959', FALSE),
(11, '1975', FALSE),
(11, '1985', FALSE),
(12, 'Una teoría física que describe la gravedad', TRUE),
(12, 'Una teoría sobre la electricidad', FALSE),
(12, 'Una teoría sobre la genética', FALSE),
(12, 'Una teoría sobre la química', FALSE),
(13, 'El Amazonas', TRUE),
(13, 'El Nilo', FALSE),
(13, 'El Yangtsé', FALSE),
(13, 'El Mississippi', FALSE),
(14, 'Cristóbal Colón', TRUE),
(14, 'Ferdinand Magellan', FALSE),
(14, 'Marco Polo', FALSE),
(14, 'Juan Sebastián Elcano', FALSE),
(15, 'León', TRUE),
(15, 'Tigre', FALSE),
(15, 'Elefante', FALSE),
(15, 'Cebra', FALSE),
(16, 'Marte', TRUE),
(16, 'Venus', FALSE),
(16, 'Júpiter', FALSE),
(16, 'Saturno', FALSE),
(17, 'Portugués', TRUE),
(17, 'Español', FALSE),
(17, 'Inglés', FALSE),
(17, 'Francés', FALSE),
(18, '54', TRUE),
(18, '58', FALSE),
(18, '50', FALSE),
(18, '48', FALSE),
(19, 'Perú', TRUE),
(19, 'México', FALSE),
(19, 'Chile', FALSE),
(19, 'Colombia', FALSE),
(20, 'Yuri Gagarin', TRUE),
(20, 'Neil Armstrong', FALSE),
(20, 'Buzz Aldrin', FALSE),
(20, 'Valentina Tereshkova', FALSE),
(21, '1939', TRUE),
(21, '1941', FALSE),
(21, '1935', FALSE),
(21, '1945', FALSE),
(22, 'El proceso mediante el cual las plantas producen su propio alimento', TRUE),
(22, 'El proceso mediante el cual los animales obtienen energía', FALSE),
(22, 'La conversión de nutrientes en energía', FALSE),
(22, 'El proceso de descomposición de organismos', FALSE),
(23, 'Mamífero', TRUE),
(23, 'Pescado', FALSE),
(23, 'Reptil', FALSE),
(23, 'Ave', FALSE),
(24, 'Estados Unidos', TRUE),
(24, 'Canadá', FALSE),
(24, 'Alemania', FALSE),
(24, 'Francia', FALSE),
(25, 'Yen', TRUE),
(25, 'Won', FALSE),
(25, 'Dólar', FALSE),
(25, 'Euro', FALSE),
(26, 'El estudio de la materia y la energía', TRUE),
(26, 'El estudio de las emociones humanas', FALSE),
(26, 'El estudio de las relaciones sociales', FALSE),
(26, 'El estudio de los animales', FALSE),
(27, '7', TRUE),
(27, '6', FALSE),
(27, '8', FALSE),
(27, '9', FALSE),
(28, 'Isaac Newton', TRUE),
(28, 'Nikola Tesla', FALSE),
(28, 'Albert Einstein', FALSE),
(28, 'Galileo Galilei', FALSE),
(29, 'Asia', TRUE),
(29, 'África', FALSE),
(29, 'Europa', FALSE),
(29, 'Oceanía', FALSE),
(30, 'El Pacífico', TRUE),
(30, 'El Atlántico', FALSE),
(30, 'El Índico', FALSE),
(30, 'El Ártico', FALSE),
(31, '1914', TRUE),
(31, '1918', FALSE),
(31, '1939', FALSE),
(31, '1945', FALSE),
(32, 'La explicación de cómo comenzó el universo', TRUE),
(32, 'La descripción de cómo la Tierra se formó', FALSE),
(32, 'La descripción de las primeras estrellas', FALSE),
(32, 'La teoría sobre los agujeros negros', FALSE),
(33, 'China', TRUE),
(33, 'Japón', FALSE),
(33, 'Corea del Sur', FALSE),
(33, 'India', FALSE),
(34, 'Madrid', TRUE),
(34, 'Barcelona', FALSE),
(34, 'Sevilla', FALSE),
(34, 'Valencia', FALSE),
(35, 'Pu Yi', TRUE),
(35, 'Mao Zedong', FALSE),
(35, 'Sun Yat-sen', FALSE),
(35, 'Deng Xiaoping', FALSE),
(36, 'Hidrógeno', TRUE),
(36, 'Helio', FALSE),
(36, 'Oxígeno', FALSE),
(36, 'Carbono', FALSE),
(37, 'Gato', TRUE),
(37, 'Perro', FALSE),
(37, 'Elefante', FALSE),
(37, 'Caballo', FALSE),
(38, 'Atlántico', TRUE),
(38, 'Pacífico', FALSE),
(38, 'Índico', FALSE),
(38, 'Ártico', FALSE),
(39, 'China', TRUE),
(39, 'India', FALSE),
(39, 'Estados Unidos', FALSE),
(39, 'Indonesia', FALSE),
(40, 'Cambio climático', TRUE),
(40, 'Contaminación', FALSE),
(40, 'Deforestación', FALSE),
(40, 'Escasez de agua', FALSE),
(41, 'Una estrella', TRUE),
(41, 'Un planeta', FALSE),
(41, 'Un cometa', FALSE),
(41, 'Un satélite', FALSE),
(42, '8', TRUE),
(42, '7', FALSE),
(42, '9', FALSE),
(42, '10', FALSE),
(43, 'Guepardo', TRUE),
(43, 'León', FALSE),
(43, 'Tigre', FALSE),
(43, 'Elefante', FALSE),
(44, 'Nueva York', TRUE),
(44, 'Los Ángeles', FALSE),
(44, 'Chicago', FALSE),
(44, 'Houston', FALSE),
(45, 'Sistema planetario', TRUE),
(45, 'Estrella', FALSE),
(45, 'Cometa', FALSE),
(45, 'Nebulosa', FALSE),
(46, 'Ciencias naturales', TRUE),
(46, 'Filosofía', FALSE),
(46, 'Geografía', FALSE),
(46, 'Historia', FALSE),
(47, 'Inglés', TRUE),
(47, 'Español', FALSE),
(47, 'Francés', FALSE),
(47, 'Alemán', FALSE),
(48, '11', TRUE),
(48, '10', FALSE),
(48, '9', FALSE),
(48, '8', FALSE),
(49, 'Italia', TRUE),
(49, 'Francia', FALSE),
(49, 'España', FALSE),
(49, 'Portugal', FALSE),
(50, 'Un huracán', TRUE),
(50, 'Un tornado', FALSE),
(50, 'Un terremoto', FALSE),
(50, 'Una tormenta eléctrica', FALSE);


